update bootstrap functionality

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,22 +1,30 @@
 #!/usr/bin/env bash
 
-set -eu
+set -e
+shopt -s globstar
 
 # Directory to look for bootstrap executables in
 BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
-
 if [[ ! -d "$BOOTSTRAP_D" ]]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    echo "Bootstrap directory '${BOOTSTRAP_D}' not found" >&2
     exit 1
 fi
 
-find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+# Load global functions
+. "$BOOTSTRAP_D/.global.sh"
+
+# Execute all bootstrap files in glob order
+log "Bootstrapping system"
+for bootstrap in "$BOOTSTRAP_D"/*; do
     if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        filename=$(basename "$bootstrap")
+        log "Executing bootstrap for '${filename}'..."
         if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
+            log "bootstrap '${bootstrap}' failed" >&2
             exit 1
         fi
     fi
 done
 
-echo "Bootstrap completed"
+log "Bootstrap completed"
+
